project_id = "uspmulzpfnspivqdklsz"

[functions.import-products]
verify_jwt = true

[functions.identify-product]
verify_jwt = true

[functions.search-products]
verify_jwt = true

[functions.suggest-alternatives]
verify_jwt = true